register_keys:
  cloud_raw_confidence_threshold: 35
  custom_init_pos:
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 1.0
  custom_map_mode: 0
  devstatuslog: 1
  dtof_fps: 100
  enable_imu_smooth: 0
  image_mask_abs_path: ''
  imu_smooth_frequency: 1000
  mapping_result_dest_dir: ''
  mapping_result_file_name: ''
  overlay_alpha: 0.6
  overlay_camera_topic: /odin1/image/undistorted
  overlay_output_topic: /odin1/overlay_image
  overlay_reprojected_topic: /odin1/reprojected_image
  pubintensitygray: 0
  recorddata: 0
  relocalization_map_abs_path: /home/xjturm/xjtu_nav26/src/odin_ros_driver/map/20260521_223913/map_20260521_224044.bin
  resetalgo: 0
  save_log: 0
  send_odom_baselink_tf: 1
  sendcloudrender: 1
  sendcloudslam: 1
  senddepth: 0
  senddtof: 1
  sendimagemask: 0
  sendimu: 1
  sendodom: 1
  sendoverlay: 0
  sendreprojection: 0
  sendrgb: 1
  sendrgbcompressed: 1
  sendrgbundistort: 0
  showcamerapose: 0
  showpath: 0
  streamctrl: 1
  strict_usb3.0_check: 0
  use_host_ros_time: 1
